### ISSUE TITLE
Noob Question Regarding Icon

### ISSUE THREAD

**Issue by RGSMA** [ivan-aleksandrov/homebridge-powerloss-ifttt-notifier#1]
Your plugin is installed and working perfectly. Noob question… should the icon read "Not Supported"

Thanks

![img_2306](https://user-images.githubusercontent.com/41753619/43591742-fed224de-9641-11e8-8579-9dd7aebf41e1.PNG)

**Comment by ivan-aleksandrov** [comment]
@RGSMA - yep, it is working but sadly it will show as 'not supported' because Apple HomeKit does not have such a 'reporting' device to be used.
I've left it in the 'Default Room' in my setup so it isn't showing in the rooms I use with other plugins.

**Comment by RGSMA** [comment]
Thanks for the quick response. It works great.
